# Server settings
server:
    port:8080
    address:localhost



# SPRING PROFILES
spring:
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true
    datasource:
            name: test
            url: jdbc:mysql://localhost:3306/mcfield?useUnicode=true&amp;charaterEncoding=utf-8
            username: root
            password:
            # 使用HikariCP数据源
            type: com.zaxxer.hikari.HikariDataSource
            connectionTestQuery: SELECT 1
            cachePrepStmts: true
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048


# MyBatis
mybatis:
    typeAliasesPackage: com.echounion.mc.modules.**.entity
    mapperLocations: classpath:/mapping/**/*.xml
    configLocation: classpath:/mybatis-config.xml

# LOGGING
logging:
    level:
       com.ibatis:DEBUG